/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telatriangulo;

/**
 *
 * @author Impressão
 */
public class TelaTriangulos extends javax.swing.JFrame {

    /**
     * Creates new form TelaTriangulos
     */
    public TelaTriangulos() {
        initComponents();
        painelRespotas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnSegmentoA = new javax.swing.JSlider();
        spnSegmentoB = new javax.swing.JSlider();
        spnSegmentoC = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valorSegA = new javax.swing.JLabel();
        valorSegB = new javax.swing.JLabel();
        valorSegC = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        painelRespotas = new javax.swing.JPanel();
        lblETriangulo = new javax.swing.JLabel();
        lblTipoTriangulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        spnSegmentoA.setMaximum(20);
        spnSegmentoA.setMinorTickSpacing(1);
        spnSegmentoA.setSnapToTicks(true);
        spnSegmentoA.setValue(0);
        spnSegmentoA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSegmentoAStateChanged(evt);
            }
        });

        spnSegmentoB.setMaximum(20);
        spnSegmentoB.setSnapToTicks(true);
        spnSegmentoB.setValue(0);
        spnSegmentoB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSegmentoBStateChanged(evt);
            }
        });

        spnSegmentoC.setMaximum(20);
        spnSegmentoC.setSnapToTicks(true);
        spnSegmentoC.setValue(0);
        spnSegmentoC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSegmentoCStateChanged(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("<html> Segmento <b>a</b></html>");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("<html> Segmento <b>b</b></html>");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("<html> Segmento <b>c</b></html>");

        valorSegA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valorSegA.setForeground(new java.awt.Color(153, 153, 153));
        valorSegA.setText("0");

        valorSegB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valorSegB.setForeground(new java.awt.Color(153, 153, 153));
        valorSegB.setText("0");

        valorSegC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valorSegC.setForeground(new java.awt.Color(153, 153, 153));
        valorSegC.setText("0");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/triangulo_escaleno_001-600x338.png"))); // NOI18N

        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblETriangulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblETriangulo.setForeground(new java.awt.Color(51, 51, 255));
        lblETriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblETriangulo.setText("Forma um Triângulo");

        lblTipoTriangulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTipoTriangulo.setForeground(new java.awt.Color(255, 51, 51));
        lblTipoTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoTriangulo.setText("Equilátero");

        javax.swing.GroupLayout painelRespotasLayout = new javax.swing.GroupLayout(painelRespotas);
        painelRespotas.setLayout(painelRespotasLayout);
        painelRespotasLayout.setHorizontalGroup(
            painelRespotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRespotasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblETriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(painelRespotasLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(lblTipoTriangulo)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        painelRespotasLayout.setVerticalGroup(
            painelRespotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRespotasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblETriangulo)
                .addGap(18, 18, 18)
                .addComponent(lblTipoTriangulo)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(painelRespotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spnSegmentoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spnSegmentoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(spnSegmentoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorSegA)
                            .addComponent(valorSegB)
                            .addComponent(valorSegC))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnSegmentoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorSegA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnSegmentoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorSegB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnSegmentoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorSegC))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelRespotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnSegmentoAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSegmentoAStateChanged
        // TODO add your handling code here:
        valorSegA.setText(Integer.toString(spnSegmentoA.getValue()));
    }//GEN-LAST:event_spnSegmentoAStateChanged

    private void spnSegmentoBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSegmentoBStateChanged
        // TODO add your handling code here:
        valorSegB.setText(Integer.toString(spnSegmentoB.getValue()));
    }//GEN-LAST:event_spnSegmentoBStateChanged

    private void spnSegmentoCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSegmentoCStateChanged
        // TODO add your handling code here:
        valorSegC.setText(Integer.toString((spnSegmentoC.getValue())));
    }//GEN-LAST:event_spnSegmentoCStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        painelRespotas.setVisible(true);
        int a, b, c;
        a = spnSegmentoA.getValue();
        b = spnSegmentoB.getValue();
        c = spnSegmentoC.getValue();
        
        if (a<b+c && b<a+c && c<a+b){
            lblETriangulo.setText("Forma um Triângulo");
            if (a == b && b == c){
                lblTipoTriangulo.setText("Equilátero");
            } else if (a != b && b != c && a != c){
                lblTipoTriangulo.setText("Escaleno");
            } else{
                lblTipoTriangulo.setText("Isóceles");
            }
        } else {
            lblETriangulo.setText("Não forma um Triângulo");
            lblTipoTriangulo.setText(" ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTriangulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblETriangulo;
    private javax.swing.JLabel lblTipoTriangulo;
    private javax.swing.JPanel painelRespotas;
    private javax.swing.JSlider spnSegmentoA;
    private javax.swing.JSlider spnSegmentoB;
    private javax.swing.JSlider spnSegmentoC;
    private javax.swing.JLabel valorSegA;
    private javax.swing.JLabel valorSegB;
    private javax.swing.JLabel valorSegC;
    // End of variables declaration//GEN-END:variables
}
